[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn"]

<<<<<<< HEAD
[phases.install]
cmds = ["yarn install --frozen-lockfile --production=false"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"
=======
[phases.build]
cmds = ["yarn install --frozen-lockfile", "yarn build"]

[start]
cmd = "yarn start"
>>>>>>> 5a669257dafd3bcbca9f624b5f10f711dc8f62af
